# Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
#
# SPDX-License-Identifier: MIT

---
galaxy_info:
  author: Advanced Micro Devices, Inc.
  description: Export an existing LVM filesystem via NFS over RDMA.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - all

dependencies: []
