---
- name: Create required directories
  ansible.builtin.include_tasks: prep_dirs.yml

- name: Deploy docker-compose stack
  ansible.builtin.include_tasks: deploy_compose.yml

- name: Install systemd unit for stack
  ansible.builtin.include_tasks: install_service.yml
  when: aai_day_install_systemd_unit | bool
