# Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
#
# SPDX-License-Identifier: MIT

---
- name: Reload prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: Reload systemd and restart grafana-server
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
    daemon_reload: true
