matrix:
  - name: Markdown
    aspell:
      lang: en
    dictionary:
      wordlists:
        - .wordlist.txt
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - markdown.extensions.fenced_code:
      - pyspelling.filters.html:
          ignores:
            - code
            - pre
    sources:
      - '**/*.md'
    excludes:
      - '.docs-remove/**'
    default_encoding: utf-8

  - name: HTML
    aspell:
      lang: en
    dictionary:
      wordlists:
        - .wordlist.txt
      encoding: utf-8
    pipeline:
      - pyspelling.filters.html:
          ignores:
            - code
            - pre
            - style
            - script
    sources:
      - '.github/pages/*.html'
    default_encoding: utf-8
