apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  template:
    spec:
      containers:
        - name: modelserver
          volumeMounts:
            - name: bnxt
              mountPath: "/usr/lib/x86_64-linux-gnu/libibverbs/libbnxt_re-rdmav34.so"
              readOnly: true
      volumes:
        - name: bnxt
          hostPath:
            path: /usr/local/lib/libbnxt_re-rdmav34.so
            type: File
