apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../submodules/llm-d/guides/optimized-baseline/modelserver/amd/vllm

patches:
  - target:
      kind: Deployment
      name: decode
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: decode
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/vcave/vllm:rocm_721-vllm_20260423b-lmcache
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - "Qwen/Qwen3-32B"
          - "--disable-access-log-for-endpoints=/health,/metrics,/v1/models"
          - "--tensor-parallel-size=2"
          - "--gpu-memory-utilization=0.95"

  - target:
      kind: Deployment
      name: decode
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            amd.com/gpu: 2
            cpu: "32"
            memory: 100Gi
          requests:
            amd.com/gpu: 2
            cpu: "32"
            memory: 100Gi
