---
- name: Install NVMe-oF packages
  ansible.builtin.apt:
    name: "{{ nvmeof_packages }}"
    state: present
    update_cache: true

- name: Configure NVMe-oF target
  ansible.builtin.include_tasks: target.yml
  when: nvmeof_setup_minimal_role == 'target'

- name: Configure NVMe-oF initiator
  ansible.builtin.include_tasks: initiator.yml
  when: nvmeof_setup_minimal_role == 'initiator'
