---
- name: Create namespace {{ _nvmeof_ns_idx + 1 }} directory
  ansible.builtin.file:
    path: "/sys/kernel/config/nvmet/subsystems/{{ nvmeof_setup_nqn }}/namespaces/{{ _nvmeof_ns_idx + 1 }}"
    state: directory
    mode: "0755"

- name: Set namespace {{ _nvmeof_ns_idx + 1 }} device path
  ansible.builtin.copy:
    content: "{{ _nvmeof_device }}\n"
    dest: "/sys/kernel/config/nvmet/subsystems/{{ nvmeof_setup_nqn }}/namespaces/{{ _nvmeof_ns_idx + 1 }}/device_path"
    mode: "0644"

- name: Enable namespace {{ _nvmeof_ns_idx + 1 }}
  ansible.builtin.copy:
    content: "1\n"
    dest: "/sys/kernel/config/nvmet/subsystems/{{ nvmeof_setup_nqn }}/namespaces/{{ _nvmeof_ns_idx + 1 }}/enable"
    mode: "0644"
