---
# Set true to install ROCm drivers from AMD's apt repository.
# Set false when drivers are pre-installed on the host.
host_setup_enable_rocm_install: false

host_setup_enable_prometheus_node_exporter: true
host_setup_node_exporter_textfile_dir: /var/lib/node_exporter/textfile_collector
host_setup_node_exporter_extra_args: []

# Docker packages to install.
host_setup_docker_packages:
  - docker.io
  - docker-compose-plugin
  - python3-docker

extra_packages: []
