# Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
#
# SPDX-License-Identifier: MIT

---
- name: Enable and start prometheus-node-exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: true
  when: "'prometheus-node-exporter' in (extra_packages | default([]))"
