apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../submodules/llm-d/guides/optimized-baseline/modelserver/amd/sglang

patches:
  - target:
      kind: Deployment
      name: decode
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: decode
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: docker.io/lmsysorg/sglang:v0.5.10.post1-rocm720-mi30x
      - op: replace
        path: /spec/template/spec/containers/0/command
        value: ["sglang", "serve"]
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - "--model-path=Qwen/Qwen3-0.6B"
          - "--host=0.0.0.0"
          - "--port=8000"
          - "--enable-metrics"
          - "--log-level-http=warning"
          - "--tensor-parallel-size=1"

  - target:
      kind: Deployment
      name: decode
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            amd.com/gpu: 1
            cpu: "32"
            memory: 100Gi
          requests:
            amd.com/gpu: 1
            cpu: "32"
            memory: 100Gi
