---
nfs_rdma_server_ip: ""
nfs_rdma_export_path: /srv/aai-day-cache
nfs_rdma_client_mount: /mnt/lmcache-nfs
nfs_rdma_port: 20049
nfs_rdma_mount_options: rw,proto=rdma,port=20049,vers=4.2,noatime,_netdev

nfs_rdma_client_packages:
  - nfs-common
  - rdma-core
  - ibverbs-utils
  - infiniband-diags

nfs_rdma_client_modules:
  - xprtrdma
nfs_rdma_persist_modules: true
nfs_rdma_client_modules_file: /etc/modules-load.d/aai-day-nfs-rdma-client.conf
nfs_rdma_mount_fstype: nfs4
