name: rocm-aic - Spell Check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: rojopolis/spellcheck-github-actions@v0
        name: Spellcheck
